services:
  backend:
    image: jameskamwendo/iotman-backend:latest
    ports:
      - "8000:8000"
    env_file: config/.env
    volumes:
      - ./backend:/app
    command: /bin/bash -c "cat ./iotman+_art.txt && chmod +x /app/start.sh && /app/start.sh"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: jameskamwendo/iotman-ui:latest
    ports:
      - "3000:3000"
    volumes:
      - ./iotman-ui:/code
    command: node .next/standalone/server.js
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge